export type PlanTier = "free" | "lite" | "premium" | "max";

export interface DashboardModel {
  id: string;
  name: string;
  description: string;
  provider: string;
  context_length: string;
  input_price: number;
  output_price: number;
  tiers: PlanTier[];
  gradient: "purple" | "amber" | "coral";
  logo?: string;
}

export const dashboardModels: DashboardModel[] = [
  {
    id: "route/minimax-m2.5",
    name: "MiniMax M2.5",
    description: "Balanced performance and speed",
    provider: "minimax",
    context_length: "100K",
    input_price: 0.193,
    output_price: 1.238,
    tiers: ["lite", "premium", "max"],
    gradient: "amber",
    logo: "/model-logos/route-minimax.png",
  },
  {
    id: "route/minimax-m2.5-highspeed",
    name: "MiniMax M2.5 Highspeed",
    description: "Same as M2.5 with faster output ~70 tokens/sec",
    provider: "minimax",
    context_length: "100K",
    input_price: 0.193,
    output_price: 1.238,
    tiers: ["premium", "max"],
    gradient: "coral",
    logo: "/model-logos/route-minimax.png",
  },
  {
    id: "route/minimax-m2.7",
    name: "MiniMax M2.7",
    description: "High-performance reasoning model with 100K context",
    provider: "minimax",
    context_length: "100K",
    input_price: 0.33,
    output_price: 1.32,
    tiers: ["premium", "max"],
    gradient: "purple",
    logo: "/model-logos/route-minimax.png",
  },
  {
    id: "route/minimax-m2.7-highspeed",
    name: "MiniMax M2.7 Highspeed",
    description: "M2.7 with faster output ~100 tokens/sec",
    provider: "minimax",
    context_length: "100K",
    input_price: 0.33,
    output_price: 1.32,
    tiers: ["lite", "premium", "max"],
    gradient: "coral",
    logo: "/model-logos/route-minimax.png",
  },
  {
    id: "route/kimi-k2.5",
    name: "Kimi K2.5",
    description: "Long context understanding with excellent reasoning",
    provider: "kimi",
    context_length: "131K",
    input_price: 0.462,
    output_price: 2.42,
    tiers: ["free", "lite", "premium", "max"],
    gradient: "coral",
    logo: "/model-logos/route-kimi.png",
  },
  {
    id: "route/kimi-k2.5-highspeed",
    name: "Kimi K2.5 Highspeed",
    description: "Kimi K2.5 with faster output ~100 tokens/sec",
    provider: "kimi",
    context_length: "131K",
    input_price: 0.6468,
    output_price: 3.388,
    tiers: ["lite", "premium", "max"],
    gradient: "purple",
    logo: "/model-logos/route-kimi.png",
  },
  {
    id: "route/glm-5",
    name: "glm-5",
    description: "Latest generation GLM with enhanced reasoning",
    provider: "zai",
    context_length: "200K",
    input_price: 0.792,
    output_price: 2.53,
    tiers: ["free", "lite", "premium", "max"],
    gradient: "purple",
    logo: "/model-logos/route-zai.svg",
  },
  {
    id: "route/glm-5-highspeed",
    name: "glm-5-highspeed",
    description: "glm-5 tuned for faster response times",
    provider: "zai",
    context_length: "200K",
    input_price: 1.1088,
    output_price: 3.542,
    tiers: ["max"],
    gradient: "coral",
    logo: "/model-logos/route-zai.svg",
  },
  {
    id: "route/glm-5.1",
    name: "glm-5.1",
    description: "Enhanced GLM with improved capabilities",
    provider: "zai",
    context_length: "200K",
    input_price: 1,
    output_price: 3,
    tiers: ["lite", "premium", "max"],
    gradient: "purple",
    logo: "/model-logos/route-zai.svg",
  },
  {
    id: "route/glm-5.1-precision",
    name: "glm-5.1-precision",
    description: "glm-5.1 variant tuned for higher precision tasks",
    provider: "zai",
    context_length: "200K",
    input_price: 1.2,
    output_price: 3.5,
    tiers: ["lite", "premium", "max"],
    gradient: "purple",
    logo: "/model-logos/route-zai.svg",
  },
  {
    id: "route/glm-4.7",
    name: "glm-4.7",
    description: "Earlier GLM release with strong general-purpose performance",
    provider: "zai",
    context_length: "200K",
    input_price: 1.32,
    output_price: 4.4,
    tiers: ["lite", "premium", "max"],
    gradient: "purple",
    logo: "/model-logos/route-zai.svg",
  },
  {
    id: "route/glm-4.7-flash",
    name: "glm-4.7-flash",
    description: "Lower-latency GLM 4.7 variant",
    provider: "zai",
    context_length: "200K",
    input_price: 1.32,
    output_price: 4.4,
    tiers: ["lite", "premium", "max"],
    gradient: "purple",
    logo: "/model-logos/route-zai.svg",
  },
  {
    id: "route/qwen3.5-9b",
    name: "Qwen3.5 9B",
    description: "Compact Qwen model for fast, low-cost workloads",
    provider: "qwen",
    context_length: "131K",
    input_price: 0.2,
    output_price: 0.6,
    tiers: ["free", "lite", "premium", "max"],
    gradient: "amber",
    logo: "/model-logos/route-qwen.png",
  },
  {
    id: "route/qwen3.5-397b-a17b",
    name: "Qwen3.5 397B A17B",
    description: "Large 397B parameter model",
    provider: "qwen",
    context_length: "262K",
    input_price: 1.1,
    output_price: 3.3,
    tiers: ["free", "lite", "premium", "max"],
    gradient: "amber",
    logo: "/model-logos/route-qwen.png",
  },
  {
    id: "route/deepseek-v3.2",
    name: "DeepSeek V3.2",
    description: "Advanced reasoning model",
    provider: "deepseek",
    context_length: "164K",
    input_price: 0.4928,
    output_price: 0.7392,
    tiers: ["free", "lite", "premium", "max"],
    gradient: "coral",
    logo: "/model-logos/route-deepseek.png",
  },
  {
    id: "route/deepseek-v3.2-speciale",
    name: "DeepSeek V3.2 Speciale",
    description: "Special edition DeepSeek model with enhanced capabilities",
    provider: "chutes",
    context_length: "164K",
    input_price: 0.55,
    output_price: 0.82,
    tiers: ["max"],
    gradient: "purple",
    logo: "/model-logos/route-deepseek.png",
  },
  {
    id: "route/deepseek-r1",
    name: "DeepSeek R1",
    description: "Advanced reasoning with chain-of-thought",
    provider: "chutes",
    context_length: "163K",
    input_price: 0.495,
    output_price: 2.365,
    tiers: ["max"],
    gradient: "amber",
    logo: "/model-logos/route-deepseek.png",
  },
  {
    id: "route/mimo-v2-omni",
    name: "MiMo V2 Omni",
    description: "Xiaomi multimodal model for versatile tasks",
    provider: "opencode",
    context_length: "256K",
    input_price: 0.55,
    output_price: 1.65,
    tiers: ["premium", "max"],
    gradient: "amber",
    logo: "/model-logos/route-xiaomi.png",
  },
  {
    id: "route/mimo-v2-pro",
    name: "MiMo V2 Pro",
    description: "Xiaomi high-capability model for stronger outputs",
    provider: "opencode",
    context_length: "256K",
    input_price: 0.45,
    output_price: 1.35,
    tiers: ["premium", "max"],
    gradient: "amber",
    logo: "/model-logos/route-xiaomi.png",
  },
  {
    id: "route/gemma-4-31b-it",
    name: "Gemma 4 31B IT",
    description: "Google Gemma 4 instruction-tuned model for versatile tasks",
    provider: "google",
    context_length: "131K",
    input_price: 0.1,
    output_price: 0.3,
    tiers: ["free", "lite", "premium", "max"],
    gradient: "amber",
    logo: "/model-logos/route-google.svg",
  },
];

export const getDashboardModelsForTier = (tier: PlanTier) =>
  dashboardModels.filter((model) => model.tiers.includes(tier));
